In [ ]:
import numpy as np
import pandas as pd
import time
from sklearn.metrics import f1_score

In [10]:
def kl_divergence(p, q):
    eps = 1e-12
    p = np.clip(p, eps, 1)
    q = np.clip(q, eps, 1)
    return np.sum(p * np.log(p / q))

In [11]:
def sqrt_js_divergence(p, q):
    p = p.astype(float)
    q = q.astype(float)
    
    p /= p.sum()
    q /= q.sum()
    m = 0.5 * (p + q)
    
    js = 0.5 * kl_divergence(p, m) + 0.5 * kl_divergence(q, m)
    js = max(js, 0.0)
    return np.sqrt(js)

In [12]:
ms = pd.read_excel(r"C:\Users\user\Desktop\디어젠전달용\SMILES_pred\smiles_122.xlsx")
ms["m/z"] = ms["m/z"].astype(int)
ms["intensity"] = ms["intensity"].astype(float)

names = ms["Name"].drop_duplicates().reset_index(drop=True)
namesidx = {n: idx for idx, n in enumerate(names)}
ms["m/z_idx"] = (np.round(ms["m/z"]) - 1).astype(int)
ms["row_idx"] = ms["Name"].map(namesidx)

In [13]:
ms

,Name,Form,m/z,intensity,SMILES,테러 물질 여부,m/z_idx,row_idx
0,Formaldehyde,CH2O,12,10.00,C=O,X,11,0
1,Formaldehyde,CH2O,13,10.00,C=O,X,12,0
2,Formaldehyde,CH2O,14,10.00,C=O,X,13,0
3,Formaldehyde,CH2O,15,20.00,C=O,X,14,0
4,Formaldehyde,CH2O,28,240.00,C=O,X,27,0
...,...,...,...,...,...,...,...,...
3962,Glufosinate,C5H12NO4P,135,85.61,CP(=O)(CCC(C(=O)O)N)O,X,134,121
3963,Glufosinate,C5H12NO4P,136,709.59,CP(=O)(CCC(C(=O)O)N)O,X,135,121
3964,Glufosinate,C5H12NO4P,162,17.08,CP(=O)(CCC(C(=O)O)N)O,X,161,121
3965,Glufosinate,C5H12NO4P,163,16.28,CP(=O)(CCC(C(=O)O)N)O,X,162,121
3966,Glufosinate,C5H12NO4P,180,69.63,CP(=O)(CCC(C(=O)O)N)O,X,179,121

In [14]:
N = ms["row_idx"].max() + 1
D = ms["m/z_idx"].max() + 1

data = np.zeros((N, D))
grouped = ms.groupby(["row_idx", "m/z_idx"])["intensity"].max()

row_idx = grouped.index.get_level_values(0).to_numpy()
col_idx = grouped.index.get_level_values(1).to_numpy()
values = grouped.to_numpy()

data[row_idx, col_idx] = values

In [15]:
ter_label = ms[["Name", "테러 물질 여부"]].drop_duplicates().reset_index(drop=True)

In [20]:
# row_idx별 대표 Name/SMILES 만들기
meta = (ms[["row_idx", "Name"] + (["SMILES"] if "SMILES" in ms.columns else [])]
        .drop_duplicates(subset=["row_idx"])
        .sort_values("row_idx")
        .reset_index(drop=True))
meta

,row_idx,Name,SMILES
0,0,Formaldehyde,C=O
1,1,Methyl hydrazine,CNN
2,2,Formic acid,C(=O)O
3,3,Methyl chloride,CCl
4,4,Methylamine,CN
...,...,...,...
117,117,Acetaminophen,CC(=O)NC1=CC=C(C=C1)O
118,118,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O
119,119,Paraquat dichloride,C[N+]1=CC=C(C=C1)C2=CC=[N+](C=C2)C.[Cl-].[Cl-]
120,120,N-(Phosphonomethyl)glycine,C(C(=O)O)NCP(=O)(O)O
121,121,Glufosinate,CP(=O)(CCC(C(=O)O)N)O

In [24]:
noise_set = [0.03, 0.05, 0.10]
case_set = [[1, 1], [1, -1], [-1, 1], [-1, -1]]

noise = noise_set[0]
case = case_set[0]

avg_acc = np.zeros(len(noise_set))


for k in range(N):
    noise_data = data[k].copy()
    
    idx = data[k].argsort()
    peak2 = idx[-2]
    peak3 = idx[-3]
    noise_data[peak2] = data[k][peak2] * (1 + (noise * case[0]))
    noise_data[peak3] = data[k][peak3] * (1 + (noise * case[1]))
    
    noise_data /= noise_data.sum()
    
    jsd = np.zeros(N)
    
    for l in range(N):
        jsd[l] = sqrt_js_divergence(noise_data, data[l])
        
    pred = jsd.argmin()

    # 출력
    name_k = meta.loc[k, "Name"]
    name_p = meta.loc[pred, "Name"]

    if "SMILES" in meta.columns:
        smi_k = meta.loc[k, "SMILES"]
        smi_p = meta.loc[pred, "SMILES"]
        print(f"{name_k} ({smi_k})  -->  pred={pred}: {name_p} ({smi_p})")
    else:
        print(f"[k={k}] {name_k}  -->  pred={pred}: {name_p}")

Formaldehyde (C=O)  -->  pred=0: Formaldehyde (C=O)
Methyl hydrazine ( CNN )  -->  pred=1: Methyl hydrazine ( CNN )
Formic acid (C(=O)O  )  -->  pred=2: Formic acid (C(=O)O  )
Methyl chloride ( CCl  )  -->  pred=3: Methyl chloride ( CCl  )
Methylamine (CN )  -->  pred=4: Methylamine (CN )
Hydrogen cyanide (C#N )  -->  pred=5: Hydrogen cyanide (C#N )
Vinyl chloride (C=CCl )  -->  pred=6: Vinyl chloride (C=CCl )
Ethylene oxide (C1CO1 )  -->  pred=7: Ethylene oxide (C1CO1 )
Trimethylamine (CN(C)C  )  -->  pred=8: Trimethylamine (CN(C)C  )
Propylene oxide (CC1CO1)  -->  pred=9: Propylene oxide (CC1CO1)
Methyl ethyl ketone (CCC(=O)C)  -->  pred=10: Methyl ethyl ketone (CCC(=O)C)
Methyl vinyl ketone (CC(=O)C=C )  -->  pred=11: Methyl vinyl ketone (CC(=O)C=C )
Acrylic acid (C=CC(=O)O )  -->  pred=12: Acrylic acid (C=CC(=O)O )
Methyl acrylate (COC(=O)C=C )  -->  pred=13: Methyl acrylate (COC(=O)C=C )
Nitrobenzene (C1=CC=C(C=C1)[N+](=O)[O-])  -->  pred=14: Nitrobenzene (C1=CC=C(C=C1)[N+](=O)[O-])
p-Nitrotoluene (CC1=CC=C(C=C1)[N+](=O)[O-] )  -->  pred=15: p-Nitrotoluene (CC1=CC=C(C=C1)[N+](=O)[O-] )
Benzyl chloride (C1=CC=C(C=C1)CCl  )  -->  pred=16: Benzyl chloride (C1=CC=C(C=C1)CCl  )
Acrolein (C=CC=O  )  -->  pred=17: Acrolein (C=CC=O  )
Allyl chloride (C=CCCl  )  -->  pred=18: Allyl chloride (C=CCCl  )
Acrylonitrile (C=CC#N)  -->  pred=19: Acrylonitrile (C=CC#N)
Ethylenediamine (C(CN)N )  -->  pred=20: Ethylenediamine (C(CN)N )
Allyl alcohol (C=CCO )  -->  pred=21: Allyl alcohol (C=CCO )
m-Cresol (CC1=CC(=CC=C1)O)  -->  pred=22: m-Cresol (CC1=CC(=CC=C1)O)
Phenol (C1=CC=C(C=C1)O )  -->  pred=23: Phenol (C1=CC=C(C=C1)O )
1-Butanamine (CCCCN )  -->  pred=24: 1-Butanamine (CCCCN )
Triethylamine (CCN(CC)CC  )  -->  pred=25: Triethylamine (CCN(CC)CC  )
Acetic acid ethyl ester (CCOC(=O)C  )  -->  pred=26: Acetic acid ethyl ester (CCOC(=O)C  )
Ethylenimine ( C1CN1)  -->  pred=27: Ethylenimine ( C1CN1)
Benzene, 2,4-diisocyanato-1-methyl- (CC1=C(C=C(C=C1)N=C=O)N=C=O )  -->  pred=28: Benzene, 2,4-diisocyanato-1-methyl- (CC1=C(C=C(C=C1)N=C=O)N=C=O )
Acrylyl chloride (C=CC(=O)Cl  )  -->  pred=29: Acrylyl chloride (C=CC(=O)Cl  )
Isophorone diisocyanate (CC1(CC(CC(C1)(C)CN=C=O)N=C=O)C )  -->  pred=30: Isophorone diisocyanate (CC1(CC(CC(C1)(C)CN=C=O)N=C=O)C )
Sulfuric Acid (OS(=O)(=O)O )  -->  pred=31: Sulfuric Acid (OS(=O)(=O)O )
Nitric acid ([N+](=O)(O)[O-]  )  -->  pred=32: Nitric acid ([N+](=O)(O)[O-]  )
Phosphorus trichloride ( P(Cl)(Cl)Cl  )  -->  pred=33: Phosphorus trichloride ( P(Cl)(Cl)Cl  )
Chlorine (ClCl)  -->  pred=34: Chlorine (ClCl)
Arsine ([AsH3]  )  -->  pred=35: Arsine ([AsH3]  )
Phosphorus oxychloride (O=P(Cl)(Cl)Cl)  -->  pred=36: Phosphorus oxychloride (O=P(Cl)(Cl)Cl)
Chlorine dioxide ( O=Cl[O]  )  -->  pred=37: Chlorine dioxide ( O=Cl[O]  )
Diborane (B.B  )  -->  pred=38: Diborane (B.B  )
Nitric oxide ([N]=O  )  -->  pred=39: Nitric oxide ([N]=O  )
Methane, nitro- (C[N+](=O)[O-]  )  -->  pred=40: Methane, nitro- (C[N+](=O)[O-]  )
Ammonium nitrate ([NH4+].[N+](=O)([O-])[O-]  )  -->  pred=41: Ammonium nitrate ([NH4+].[N+](=O)([O-])[O-]  )
Hexamine (C1N2CN3CN1CN(C2)C3  )  -->  pred=42: Hexamine (C1N2CN3CN1CN(C2)C3  )
Potassium chlorate ([K+].[O-][Cl+2]([O-])[O-])  -->  pred=43: Potassium chlorate ([K+].[O-][Cl+2]([O-])[O-])
Potassium nitrate ([N+](=O)([O-])[O-].[K+]  )  -->  pred=44: Potassium nitrate ([N+](=O)([O-])[O-].[K+]  )
Sodium chlorate ([O-]Cl(=O)=O.[Na+])  -->  pred=45: Sodium chlorate ([O-]Cl(=O)=O.[Na+])
Sodium nitrate ( [N+](=O)([O-])[O-].[Na+]  )  -->  pred=46: Sodium nitrate ( [N+](=O)([O-])[O-].[Na+]  )
Nickel tetracarbonyl ([C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[Ni])  -->  pred=47: Nickel tetracarbonyl ([C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[Ni])
Germane ([GeH4]  )  -->  pred=48: Germane ([GeH4]  )
Trifluoroborane ( B(F)(F)F )  -->  pred=49: Trifluoroborane ( B(F)(F)F )
Ethene, tetrafluoro- (C(=C(F)F)(F)F )  -->  pred=50: Ethene, tetrafluoro- (C(=C(F)F)(F)F )
Boron trichloride (B(Cl)(Cl)Cl  )  -->  pred=51: Boron trichloride (B(Cl)(Cl)Cl  )
1,3-Butadiene, 1,1,2,3,4,4-hexafluoro- (C(=C(F)F)(C(=C(F)F)F)F  )  -->  pred=52: 1,3-Butadiene, 1,1,2,3,4,4-hexafluoro- (C(=C(F)F)(C(=C(F)F)F)F  )
Bromine (BrBr )  -->  pred=53: Bromine (BrBr )
Isoprene (CC(=C)C=C  )  -->  pred=54: Isoprene (CC(=C)C=C  )
1,1-Dichloroethylene (C=C(Cl)Cl  )  -->  pred=55: 1,1-Dichloroethylene (C=C(Cl)Cl  )
Hexamethyl disiloxne (C[Si](C)(C)O[Si](C)(C)C)  -->  pred=56: Hexamethyl disiloxne (C[Si](C)(C)O[Si](C)(C)C)
Iron pentacarbonyl ([C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[Fe])  -->  pred=57: Iron pentacarbonyl ([C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[C-]#[O+].[Fe])
Thionyl chloride (O=S(Cl)Cl)  -->  pred=58: Thionyl chloride (O=S(Cl)Cl)
Titanium tetrachloride ( Cl[Ti](Cl)(Cl)Cl)  -->  pred=59: Titanium tetrachloride ( Cl[Ti](Cl)(Cl)Cl)
Ethene, ethoxy- (CCOC=C)  -->  pred=60: Ethene, ethoxy- (CCOC=C)
Silane ([SiH4] )  -->  pred=61: Silane ([SiH4] )
Silane, dichloromethyl- (C[Si](Cl)Cl)  -->  pred=62: Silane, dichloromethyl- (C[Si](Cl)Cl)
Methyltrichlorosilane ( C[Si](Cl)(Cl)Cl)  -->  pred=63: Methyltrichlorosilane ( C[Si](Cl)(Cl)Cl)
Trichlorovinylsilane ( C=C[Si](Cl)(Cl)Cl )  -->  pred=64: Trichlorovinylsilane ( C=C[Si](Cl)(Cl)Cl )
Trichloroethylsilane (CC[Si](Cl)(Cl)Cl  )  -->  pred=65: Trichloroethylsilane (CC[Si](Cl)(Cl)Cl  )
Silane, tetramethyl- (C[Si](C)(C)C )  -->  pred=66: Silane, tetramethyl- (C[Si](C)(C)C )
Silicon tetrachloride ([Si](Cl)(Cl)(Cl)Cl  )  -->  pred=67: Silicon tetrachloride ([Si](Cl)(Cl)(Cl)Cl  )
Carbon monoxide ([C-]#[O+]  )  -->  pred=68: Carbon monoxide ([C-]#[O+]  )
Carbon dioxide (C(=O)=O  )  -->  pred=69: Carbon dioxide (C(=O)=O  )
Nitrogen dioxide (N(=O)[O] )  -->  pred=70: Nitrogen dioxide (N(=O)[O] )
Methyl Alcohol (CO  )  -->  pred=71: Methyl Alcohol (CO  )
Sulfur dioxide (O=S=O  )  -->  pred=72: Sulfur dioxide (O=S=O  )
Hydrogen bromide (Br  )  -->  pred=73: Hydrogen bromide (Br  )
Hydrogen ([HH])  -->  pred=74: Hydrogen ([HH])
Ethylene (C=C  )  -->  pred=75: Ethylene (C=C  )
Propane (CCC  )  -->  pred=76: Propane (CCC  )
Methane (C  )  -->  pred=77: Methane (C  )
Benzene (C1=CC=CC=C1)  -->  pred=78: Benzene (C1=CC=CC=C1)
Toluene (CC1=CC=CC=C1 )  -->  pred=79: Toluene (CC1=CC=CC=C1 )
Carbon disulfide (C(=S)=S )  -->  pred=80: Carbon disulfide (C(=S)=S )
LPG(butane) (CCCC)  -->  pred=81: LPG(butane) (CCCC)
LPG(propane) (CCC  )  -->  pred=76: Propane (CCC  )
LNG(methane) (C  )  -->  pred=77: Methane (C  )
hydrazine (NN)  -->  pred=84: hydrazine (NN)
Sarin(Phosphonofluoridic acid, methyl-1-methylethyl ester) (CC(C)OP(=O)(C)F  )  -->  pred=85: Sarin(Phosphonofluoridic acid, methyl-1-methylethyl ester) (CC(C)OP(=O)(C)F  )
Phosphonofluoridic acid, methyl-, 1,2,2-trimethylpropyl ester (CC(C(C)(C)C)OP(=O)(C)F  )  -->  pred=86: Phosphonofluoridic acid, methyl-, 1,2,2-trimethylpropyl ester (CC(C(C)(C)C)OP(=O)(C)F  )
Tabun(Phosphoramidocyanidic acid, dimethyl-, ethyl ester) (CCOP(=O)(C#N)N(C)C)  -->  pred=87: Tabun(Phosphoramidocyanidic acid, dimethyl-, ethyl ester) (CCOP(=O)(C#N)N(C)C)
VX(Phosphonothioic acid, methyl-S-[2-[bis(1-methylethyl)amino]ethyl]O-ethyl ester) (CCOP(=O)(C)SCCN(C(C)C)C(C)C )  -->  pred=88: VX(Phosphonothioic acid, methyl-S-[2-[bis(1-methylethyl)amino]ethyl]O-ethyl ester) (CCOP(=O)(C)SCCN(C(C)C)C(C)C )
2-Chloroethyl ethyl sulfide (RFP 제안 물질의 25번 이름 수정 필요) (CCSCCCl  )  -->  pred=89: 2-Chloroethyl ethyl sulfide (RFP 제안 물질의 25번 이름 수정 필요) (CCSCCCl  )
Mustard Gas(Bis(2-chloroethyl)sulfide) (C(CCl)SCCCl )  -->  pred=90: Mustard Gas(Bis(2-chloroethyl)sulfide) (C(CCl)SCCCl )
Bis(2-chloroethylthio)methane (C(CCl)SCSCCCl )  -->  pred=91: Bis(2-chloroethylthio)methane (C(CCl)SCSCCCl )
1,2-Bis(2-chloroethylthio) ethane (C(CSCCCl)SCCCl  )  -->  pred=92: 1,2-Bis(2-chloroethylthio) ethane (C(CSCCCl)SCCCl  )
1,3-Bis(2-chloroethylthio)propane (C(CSCCCl)CSCCCl )  -->  pred=93: 1,3-Bis(2-chloroethylthio)propane (C(CSCCCl)CSCCCl )
1,4-Bis(2-chloroethylthio)butane (C(CCSCCCl)CSCCCl)  -->  pred=94: 1,4-Bis(2-chloroethylthio)butane (C(CCSCCCl)CSCCCl)
1,5-Bis(2-chloroethylthio)pentane ( C(CCSCCCl)CCSCCCl )  -->  pred=95: 1,5-Bis(2-chloroethylthio)pentane ( C(CCSCCCl)CCSCCCl )
Bis(2-chloroethylthiomethyl)ether (C(CCl)SCOCSCCCl  )  -->  pred=96: Bis(2-chloroethylthiomethyl)ether (C(CCl)SCOCSCCCl  )
Bis(2-chloroethylthioethyl)ether (C(CSCCCl)OCCSCCCl)  -->  pred=97: Bis(2-chloroethylthioethyl)ether (C(CSCCCl)OCCSCCCl)
Lewisite I(2-Chlorovinyl dichloro arsine) ( C(=C/[As](Cl)Cl)\Cl  )  -->  pred=98: Lewisite I(2-Chlorovinyl dichloro arsine) ( C(=C/[As](Cl)Cl)\Cl  )
Bis(2-chlorovinyl)chloroarsine (C(=C/[As](Cl)/C=C/Cl)\Cl  )  -->  pred=99: Bis(2-chlorovinyl)chloroarsine (C(=C/[As](Cl)/C=C/Cl)\Cl  )
Arsine, tris(2-chloroethenyl)- (C(=C/[As](/C=C/Cl)/C=C/Cl)\Cl )  -->  pred=100: Arsine, tris(2-chloroethenyl)- (C(=C/[As](/C=C/Cl)/C=C/Cl)\Cl )
Bis(2-chloroethyl)ethylamine (CCN(CCCl)CCCl  )  -->  pred=101: Bis(2-chloroethyl)ethylamine (CCN(CCCl)CCCl  )
Bis(2-chloroethyl)methylamine (CN(CCCl)CCCl  )  -->  pred=102: Bis(2-chloroethyl)methylamine (CN(CCCl)CCCl  )
Tris(2-chloroethyl)amine (C(CCl)N(CCCl)CCCl)  -->  pred=103: Tris(2-chloroethyl)amine (C(CCl)N(CCCl)CCCl)
Pyridine, 4-[4-(4-fluorophenyl)-2-[4-(methylsulfinyl)phenyl]-1H-imidazol-5-yl]- (CS(=O)C1=CC=C(C=C1)C2=NC(=C(N2)C3=CC=NC=C3)C4=CC=C(C=C4)F  )  -->  pred=104: Pyridine, 4-[4-(4-fluorophenyl)-2-[4-(methylsulfinyl)phenyl]-1H-imidazol-5-yl]- (CS(=O)C1=CC=C(C=C1)C2=NC(=C(N2)C3=CC=NC=C3)C4=CC=C(C=C4)F  )
Phosphorothioic acid, S-(2-(diethylamino)ethyl) O,O-diethyl ester (CCN(CC)CCSP(=O)(OCC)OCC )  -->  pred=105: Phosphorothioic acid, S-(2-(diethylamino)ethyl) O,O-diethyl ester (CCN(CC)CCSP(=O)(OCC)OCC )
1,1,3,3,3-Pentafluoro-2-(trifluoromethyl)-1-propene (C(=C(F)F)(C(F)(F)F)C(F)(F)F  )  -->  pred=106: 1,1,3,3,3-Pentafluoro-2-(trifluoromethyl)-1-propene (C(=C(F)F)(C(F)(F)F)C(F)(F)F  )
Benzeneacetic acid,α -hydroxy- α -phenyl-1-azabicyclo(2,2,2)oct-3-yl ester (C1CN2CCC1C(C2)OC(=O)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)  -->  pred=107: Benzeneacetic acid,α -hydroxy- α -phenyl-1-azabicyclo(2,2,2)oct-3-yl ester (C1CN2CCC1C(C2)OC(=O)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)
Carbonyl dichloride (C(=O)(Cl)Cl  )  -->  pred=108: Carbonyl dichloride (C(=O)(Cl)Cl  )
Cyanogen chloride (C(#N)Cl  )  -->  pred=109: Cyanogen chloride (C(#N)Cl  )
Trichloronitromethane (C([N+](=O)[O-])(Cl)(Cl)Cl  )  -->  pred=110: Trichloronitromethane (C([N+](=O)[O-])(Cl)(Cl)Cl  )
Hydrogen Nitride(ammonia) (N)  -->  pred=111: Hydrogen Nitride(ammonia) (N)
Phosphamine (P  )  -->  pred=112: Phosphamine (P  )
Hydrogen chloride (Cl )  -->  pred=113: Hydrogen chloride (Cl )
hydrogen sulfide (S)  -->  pred=114: hydrogen sulfide (S)
cyclo hexane (C1CCCCC1  )  -->  pred=115: cyclo hexane (C1CCCCC1  )
Dimethyl methylphosphonate (COP(=O)(C)OC)  -->  pred=116: Dimethyl methylphosphonate (COP(=O)(C)OC)
Acetaminophen (CC(=O)NC1=CC=C(C=C1)O  )  -->  pred=117: Acetaminophen (CC(=O)NC1=CC=C(C=C1)O  )
Aspirin (CC(=O)OC1=CC=CC=C1C(=O)O  )  -->  pred=118: Aspirin (CC(=O)OC1=CC=CC=C1C(=O)O  )
Paraquat dichloride (C[N+]1=CC=C(C=C1)C2=CC=[N+](C=C2)C.[Cl-].[Cl-])  -->  pred=119: Paraquat dichloride (C[N+]1=CC=C(C=C1)C2=CC=[N+](C=C2)C.[Cl-].[Cl-])
N-(Phosphonomethyl)glycine ( C(C(=O)O)NCP(=O)(O)O  )  -->  pred=120: N-(Phosphonomethyl)glycine ( C(C(=O)O)NCP(=O)(O)O  )
Glufosinate (CP(=O)(CCC(C(=O)O)N)O)  -->  pred=121: Glufosinate (CP(=O)(CCC(C(=O)O)N)O)